[build]
  publish = "/"
  command = ""

[forms]
  # Define form handling for the contact form
  [forms.contact]
    name = "contact"

# Handle form submissions
[[redirects]]
  from = "/success"
  to = "/index.html"
  status = 200